name: Docker

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
    tags-ignore:
      - "*"
    branches-ignore:
      - "*"

jobs:
  push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 15.10-alpine
          - 15.10-buster
          - 15.10-buster-slim
          - 15.10-stretch
          - 15.10-stretch-slim
          - lts-alpine

    name: Test & Tag Latest (node:${{ matrix.node }})

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        id: docker
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: renokico/echo-server:latest-${{ matrix.node }}

      - name: Test
        run: |
          docker run -p 6001:6001 renokico/echo-server:latest-${{ matrix.node }}
          sleep 5
          curl --silent -XGET --fail http://127.0.0.1:6001

      - name: Push
        run: |
          docker push renokico/echo-server:latest-${{ matrix.node }}
