name: Docker

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 15.10-alpine
          - 15.10-buster
          - 15.10-buster-slim
          - 15.10-stretch
          - 15.10-stretch-slim
          - lts-alpine

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    name: Test & Tag Commit (node:${{ matrix.node }})

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build test image
        id: docker_test
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: localhost:5000/renokico/echo-server:${{ github.sha }}-${{ matrix.node }}

      - name: Test
        run: |
          docker run -p 6001:6001 localhost:5000/renokico/echo-server:${{ github.sha }}-${{ matrix.node }}
          sleep 5
          curl --silent -XGET --fail http://127.0.0.1:6001

      - name: Build final image
        id: docker_final
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: renokico/echo-server:${{ github.sha }}-${{ matrix.node }}
